apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
spec:
  containers:
  - name: nfs-client
    image: gcr.io/google-samples/nfs-server:1.1
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME", "SYS_ADMIN"]