# https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
